name: Publish test results

on:
  push:
    branches: [ master ]
permissions:
  contents: write
  pages: write
  id-token: write    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        java: [24]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Install ab
        run: sudo apt-get install apache2-utils
      - name: run test
        run: ./runtests.sh ${{ matrix.java }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: java ${{ matrix.java }} result adding back to repo
#          push_options: '--force'
